# This workflow will install Python dependencies, and run tests

name: Automated Unit and Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  COMRADE_BOT_TOKEN: ${{ secrets.COMRADE_BOT_TOKEN }}
  COMRADE_MONGODB_URI: ${{ secrets.COMRADE_MONGODB_URI }}
  COMRADE_TEST_GUILD_ID: ${{ secrets.COMRADE_TEST_GUILD_ID }}
  COMRADE_TEST_MODE: True
  COMRADE_TIMEZONE: US/Eastern

jobs:
  build:
    name: Automated Test Suite

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install bot as package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test]
    - name: Test with pytest
      run: |
        pytest --cov=comrade --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
